[package]
name = "hyperngx-acme"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
instant-acme.workspace = true
rcgen.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
