# HyperNGX - HTTP-01 challenge (webroot dikelola supervisor)
location ^~ /.well-known/acme-challenge/ {
    root /var/lib/hyperngx/acme;
    default_type "text/plain";
    access_log off;
    limit_req  off;
    limit_conn off;
    try_files $uri =404;
}
