# HyperNGX - security header baseline (di-include per host)
more_clear_headers 'X-Powered-By' 'X-AspNet-Version' 'X-AspNetMvc-Version';

add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header X-Frame-Options           "SAMEORIGIN" always;
add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
add_header Permissions-Policy        "geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()" always;
add_header Cross-Origin-Opener-Policy   "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-site" always;
add_header X-Request-Id              $request_id always;
